### PR TITLE
fix: dark mode and downloading issues

### LINKED ISSUE #41: Alignment in the loading page.
Alignment in the loading page.

Delete ~/.dag/mw-keytool.jar to have it spend time redownloading this file 

[Loading page](https://cdn.discordapp.com/attachments/769094637599326228/773553984052396042/unknown.png)

### LINKED ISSUE #42: Dark mode Settings page has a white input field
**Describe the bug**
Dark mode Settings page has a white input field

[Settings page](https://cdn.discordapp.com/attachments/769094637599326228/773554283370250250/unknown.png)

**To Reproduce**
1. Login
2. Navigate to the Settings page
3. Switch to Dark Mode

**Expected behavior**
background-color of inputfield should match the css dark theme

### LINKED ISSUE #48: Replace Blocks test function with real data
**Describe the bug**
In the dashboard, the Blocks card is showing test data

Screen Shot 2020-11-04 at 1 24 51 PM

Replace this with "Block Height" card

dashboard.go line 176

resp, err := http.Get(a.Network.BlockExplorer.URL + "/snapshot/latest")
if err == nil {
            //Only need height. { "height":1338094 }
            //extract height value and send to frontend
}

Also, change updateIntervalBlocks inveral amount to 15

### LINKED ISSUE #50: UI Clean Up
**Current Behaviour:**

- In **Settings** view, under the Display Settings -> Currency, near the dropdown there is a cross button which implies that you can clear the selection. The button is misleading and does not perform any action.

image

- In the main **Dashboard** view the USD amount and number of DAG tokens use different scheme for decimal and separator (comma and period).

- In the **About** view: The spelling of "Molly" is "Moly" for the Molly Support Channel link. Also the font size/type is not consistent between the text under the About and FAQ sections.

**Proposed Behaviour:**

- In **Settings** view: Remove the cross button. The dropdown is sufficient for selecting/changing selection of displayed currency.

-  In the main **Dashboard** view: Display both DAG and USD/EUR/BTC consistently with the same separators. 

- In the **About** view: Amend "Moly" to "Molly". Also make the font type and size consistent on the page.

### PR DESCRIPTION
**Pull request by cae1um**
Close #50 
Close #48 
Close #42 
Close #41

### CODE REVIEW

File: frontend/src/pages/DownloadingScreen.vue [hunk 1]
```diff
@@ -2,9 +2,9 @@
   <div class="container">
     <div class="row">
       <div class="col-md-6 mx-auto text-center">
-        <p v-if="downloading.filename !== ''" >
+        <!-- <p v-if="downloading.filename !== ''" >
```
Comment (ffox77) [inline frontend/src/pages/DownloadingScreen.vue]: I didn't mean to delete this HTML section but the actual file it downloads so that you can test it downloading again. We need to improve the visual alignment of the text on this page. maybe make it all "centered"?

**Review by ffox77 — APPROVED** [review]
