### PR TITLE
Refactor: fix bugs

### LINKED ISSUE #27: UI Bug: Previous Transactions Duplicating when sending new Transaction
**Describe the bug**
Using an existing wallet that already has two incoming txs, when I went to send a new outgoing tx - once I hit "send transaction", my previous two txs duplicated across 8+ pages.

Logging out and logging back in cleared the issue. But now the issue is that there was no outgoing tx (despite it having arrived at the destination wallet).

**To Reproduce**
1. Go to Transactions -> Send Transaction - > Go through the whole flow
2. Click on Send Transaction
3. Scroll down to see the fullw transaction history and the two previous txs have duplicated across multiple pages

**Expected behavior**
In this instance - if I have two incoming txs and make a new outgoing tx, I expect to see 3 txs in my tx page

**Screenshots**
**Before Duplication:**
image

**After Duplication**
image
image

**After Logging out/Logging back in (outgoing wallet):**
image

**After Logging in (incoming wallet):**
image

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Catalina v 10.15.7
 - Browser [e.g. chrome, safari] Desktop App
 - Version [e.g. 22] v2.0

**Additional context**

### LINKED ISSUE #28: Bug: Link to DagExplorer does not work in Transaction Screen
**Describe the bug**
Link to DAG Explorer doesn’t work within transaction history. Right click and “open in new window” or any variety of right click and open doesn’t work. Copy and paste into google works though.

**Expected behavior**
When I click on the tx hash, I expect a new window to open up in my chrome browser with the DAG explorer link.

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### LINKED ISSUE #29: About Page hyperlinks not responding correctly
**Describe the bug**
In the about page - there are two hyperlinks: `Molly Support Channel` (for Telegram channel) and `Github page`. 

Both of these, when you click on them - open up within the Molly app itself. Instead of opening in Telegram and Chrome respectively. The user is then effectively kicked out of the wallet with no way to navigate back, except to close the application and log back in

**Expected behavior**
For Molly Support Channel hyperlink:
- Change text to: Stardust Support channel
- Opens hyperlink in Telegram app itself, not the Molly app

For Github page hyperlink:
- Opens the hyperlink in default browser

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### LINKED ISSUE #30: Bug: Language Package using incorrect month abbreviations
In Dashboard and Transactions view - the month of `May` is showing as `Mai`.

Dashboard:
image

The same thing appears in the Transactions view -> Transaction History as reported by a tester.

I suspect that the language selected may be causing this issue.

### LINKED ISSUE #31: Bug: Buttons not behaving as expected.
There are a few buttons that don't work as expected.

- After creating a new wallet, on the Terms and Conditions screen. If you click `Close Application` (instead of agree), the application doesn't actually close. You just get kicked back to the main screen. I think the easiest solution is to change the wording to `Cancel` instead.

image

**In Settings view:**

After clicking on `Wallet Information`, then `Browse`, and then **`Cancel`** - I get this screen:
image

**Expected Behaviour:** 
Cancel should just cancel with no error being thrown up. At the moment, it seems to be behaving as if you have hit apply.

### PR DESCRIPTION
**Pull request by cae1um**
Close #27 
Close #28 
Close #29 
Close #30 
Close #31 

Fixed the bug of duplicates of the previous TXs.
The cause of this bug is `initTXFromDB()` on the backend side and after fixing it, they are filtered to get a unique array.
And after logging out and logging in again, `initTxFromBlockExplorer()` is called.
I think this method doesn't return pending TXs so after some time, new TXs will appear.

### CODE REVIEW

File: frontend/src/components/Timeline.vue [hunk 1]
```diff
@@ -101,11 +105,11 @@
     </div>
     <div v-else class="text-center" style="height: 10rem;">
       <p class="card-text text-muted font-weight-bold mt-4">NO TRANSACTIONS</p>
-<!--      <p class="card-text text-muted font-italic">-->
-<!--        You have not send any transactions yet from this address. Monitoring-->
-<!--        also the received transactions will be added to the Molly wallet-->
-<!--        shortly.-->
-<!--      </p>-->
+      <!--      <p class="card-text text-muted font-italic">-->
+      <!--        You have not send any transactions yet from this address. Monitoring-->
```
Comment (StrannikAD) [inline frontend/src/components/Timeline.vue:109]: Small typo - please change `send` to `sent`

**Review by StrannikAD — APPROVED** [review]
Fantastic job - once the small typo is fixed - all looks good on my end. 🥇

**Review by ffox77 — APPROVED** [review]
